#!/bin/sh

admin=vak@cronyx.ru
USER=vak
HOME=/home/vak
DEASPASS="jf\`,,,"
export USER HOME DEASPASS

date=`date +%y%d%m`
/usr/local/bin/python /usr/local/lib/deas/backup.py |\
	/usr/local/etc/deasctl -e "$DEASPASS" |\
	gzip |\
	uuencode deas-backup-$date.gz |\
	/usr/sbin/sendmail "$admin"
